In [3]:
import numpy as np

# Array Creation

In [4]:
a=np.array([2,5,8])
print("Array a:",a)

Array a: [2 5 8]


In [5]:
b = np.arange(10,50,5)
print("Array b:",b)

Array b: [10 15 20 25 30 35 40 45]


In [6]:
d= np.zeros((2,3))
print("array d:\n",d)

array d:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [7]:
d= np.zeros((2,3),dtype=int)
print("array d:\n",d)

array d:
 [[0 0 0]
 [0 0 0]]


In [8]:
e = np.ones((3,2))
print("array e:\n",e)


array e:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [9]:
e = np.ones((3,2),dtype=int)
print("array e:\n",e)

array e:
 [[1 1]
 [1 1]
 [1 1]]


In [10]:
# creating identity matrix
f = np.eye(4) # 4*4 identity matrix
print("Identity matrix f:\n",f)

Identity matrix f:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# Array Manipulation



In [11]:
# reshape an array
a1 = np.array([1,2,3,4,5,6])
reshaped= np.reshape(a1,(2,3))
print("Reshaped array:\n",reshaped)


Reshaped array:
 [[1 2 3]
 [4 5 6]]


In [12]:
# reshape an array
a1 = np.array([1,2,3,4,5,6])
reshaped= np.reshape(a1,(3,2))
print("Reshaped array:\n",reshaped)

Reshaped array:
 [[1 2]
 [3 4]
 [5 6]]


In [13]:
# flatten in array
f1= np.array([[1,2],[3,4],[5,6],[7,8],[9,10]])
flattened  = np.ravel(f1)
print("Flattened array:",flattened)

Flattened array: [ 1  2  3  4  5  6  7  8  9 10]


In [14]:
# Transpose an array
e1 = np.array([[1, 5], [8, 7]])
transposed = np.transpose(e1)  # Transpose the array
print("Transposed array:\n", transposed) 

Transposed array:
 [[1 8]
 [5 7]]


In [15]:
# Transpose an array
e1 = np.array([[1, 5], [8, 7],[5,7]])
transposed = np.transpose(e1)  # Transpose the array
print("Transposed array:\n", transposed) 

Transposed array:
 [[1 8 5]
 [5 7 7]]


In [16]:
# Stack arrays vertically
a2 = np.array([1, 2])
b2 = np.array([3, 4])
stacked = np.vstack([a2, b2])  # Stack a and b vertically
print("Stacked arrays:\n", stacked) 

Stacked arrays:
 [[1 2]
 [3 4]]


In [17]:
# Stack arrays horizontal
a2 = np.array([1, 2])
b2 = np.array([3, 4])
stacked = np.hstack([a2, b2])  # Stack a and b vertically
print("Stacked arrays:\n", stacked) 

Stacked arrays:
 [1 2 3 4]


# Mathematical Function

In [18]:
# Add two arrays
g = np.array([1, 2, 3, 4])
added = np.add(g, 2)  # Add 2 to each element
print("Added 2 to g:", added)

Added 2 to g: [3 4 5 6]


In [19]:
# Square each element
squared = np.power(g, 2)  # Square each element
print("Squared g:", squared)

Squared g: [ 1  4  9 16]


In [26]:
# Square root of each element
sqrt_val = np.sqrt(g)  # Square root of each element
print("Square root of g:", sqrt_val)

Square root of g: [1.         1.41421356 1.73205081 2.        ]


In [27]:
print(a)
print(g)

[2 5 8]
[1 2 3 4]


In [28]:
a3 = np.array([1, 2, 3])
dot_product = np.dot(a, g)  # Dot product of a and g
print("Dot product of a1 and a:", dot_product)

ValueError: shapes (3,) and (4,) not aligned: 3 (dim 0) != 4 (dim 0)

In [30]:
a = np.array([5,6,7])
a1 = np.array([6,7,2])

In [31]:
print(a)
print(a1) 

[5 6 7]
[6 7 2]


In [32]:
a3 = np.array([1, 2, 3])
dot_product = np.dot(a1, a)  # Dot product of a and g
print("Dot product of a1 and a:", dot_product)

Dot product of a1 and a: 86


# Statistical function

In [34]:
s = np.array([10,15,20,25])
mean = np.mean(s)
print("Mean of s:", mean)

Mean of s: 17.5


In [35]:
# Standard deviation of an array
var = np.var(s)
print("Variance of s :", var)

Variance of s : 31.25


In [36]:
# Standard deviation of an array
std_dev = np.std(s)
print("Standard deviation of s:", std_dev)

Standard deviation of s: 5.5901699437494745


In [37]:
s

array([10, 15, 20, 25])

In [38]:
# Minimum element of an array
minimum = np.min(s) 
print("Min of s:", minimum)

Min of s: 10


In [39]:
# Maximum element of an array
maximum = np.max(s)
print("Max of s:", maximum)

Max of s: 25


# Random sampling 

In [49]:
# Generate random values between 0 and 1
random_vals = np.random.rand(5) # Array of 5 random values between 0 and 1
print("Random values:", random_vals) 

Random values: [0.26455561 0.77423369 0.45615033 0.56843395 0.0187898 ]


In [57]:
# Set seed for reproducibility
np.random.seed(0) 
# Generate random values between 0 and 1
random_vals = np.random.rand(5)  # Array of 3 random values between 0 and 1
print("Random values:", random_vals)

Random values: [0.5488135  0.71518937 0.60276338 0.54488318 0.4236548 ]


In [58]:
# Generate random integers 
rand_ints = np.random.randint(0, 10, size=4)  # Random integers between 0 and 10
print("Random integers:", rand_ints) 

Random integers: [5 2 4 7]


In [60]:
# Set seed for reproducibility
np.random.seed(0)
# Generate random integers
rand_ints = np.random.randint(0, 10, size=4)  # Random integers between 0 and 10
print("Random integers:", rand_ints)

Random integers: [5 0 3 3]


# Boolean & Logical

In [ ]:
# Check if all elements are True
# all
logical_test = np.array([True, False, True]) 
all_true = np.all(logical_test)  # Check if all are True
print("All elements True:", all_true)

All elements True: False


In [65]:
# Check if all elements are True
logical_test = np.array([True, True, True])
all_true = np.all(logical_test)  # Check if all are True
print("All elements True:", all_true)


All elements True: True


In [63]:
# Check if all elements are True
logical_test = np.array([False, False, False])
all_true = np.all(logical_test)  # Check if all are True
print("All elements True:", all_true)

All elements True: False


In [69]:
# Check if any elements are True
# any
logical_test = np.array([False, True, False])
any_true = np.any(logical_test)  # Check if any are True
print("Any elements True:", any_true)

Any elements True: True


# Set operations

In [70]:
# Intersection of two arrays
set_a = np.array([1, 2, 3, 4])
set_b = np.array([3, 4, 5, 6])
intersection = np.intersect1d(set_a, set_b)
print("Intersection of a and b:", intersection)

Intersection of a and b: [3 4]


In [71]:
# Union of two arrays
union = np.union1d(set_a, set_b)
print("Union of a and b:", union)

Union of a and b: [1 2 3 4 5 6]


# Array Atributes

In [76]:
# Array attributes
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9],[1,5,6]])
shape = a.shape  # Shape of the array
size = a.size    # Number of elements
dimensions = a.ndim  # Number of dimensions
dtype = a.dtype   # Data type of the array

print("Shape of a:", shape)
print("Size of a:", size)
print("Number of dimensions of a:", dimensions)
print("Data type of a:", dtype)

Shape of a: (4, 3)
Size of a: 12
Number of dimensions of a: 2
Data type of a: int64
