# NUMPY 

In [1]:
import numpy as np

In [2]:
np.__version__

'2.3.5'

In [3]:
import sys
sys.version

'3.13.9 | packaged by Anaconda, Inc. | (main, Oct 21 2025, 19:09:58) [MSC v.1929 64 bit (AMD64)]'

In [5]:
l= [0,1,2,3,4,5,6,7]
l

[0, 1, 2, 3, 4, 5, 6, 7]

In [6]:
type(l)

list

In [7]:
arr= np.array(l)
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [8]:
type(arr)

numpy.ndarray

In [9]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [10]:
np.arange(1,9)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [11]:
np.arange(5,9)

array([5, 6, 7, 8])

In [12]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [13]:
np.zeros(3) # 1d array

array([0., 0., 0.])

In [14]:
np.zeros(3 , dtype= int) # 1d array (hyperparameter tuning)

array([0, 0, 0])

In [15]:
np.zeros([2,2]) # 2d array

array([[0., 0.],
       [0., 0.]])

In [16]:
np.zeros([2,2], dtype=int)

array([[0, 0],
       [0, 0]])

In [17]:
np.zeros([10,10]) # nd array

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [18]:
np.ones(4)

array([1., 1., 1., 1.])

In [19]:
np.ones(4, dtype=int)

array([1, 1, 1, 1])

In [20]:
np.two(3)

AttributeError: module 'numpy' has no attribute 'two'

In [21]:
np.random.rand(3)

array([0.54093327, 0.37512854, 0.68321209])

In [22]:
np.random.rand(3)

array([0.95635923, 0.5702468 , 0.59342292])

In [23]:
np.random.rand(3,4)

array([[0.22156993, 0.58747292, 0.64821728, 0.79130271],
       [0.49770427, 0.2856674 , 0.62783447, 0.12797447],
       [0.96969921, 0.51858536, 0.6824591 , 0.96325731]])